import BsButton from './bs-button/BsButton.vue';
import BsButtonGroup from './bs-button-group';
import BsInput from './bs-input';
import BsRadio from './bs-radio/BsRadio.vue';
import BsRadioGroup from './bs-radio-group/BsRadioGroup.vue';
import BsCheckbox from './bs-checkbox/BsCheckbox.vue';
import BsCheckboxGroup from './bs-checkbox-group/BsCheckboxGroup.vue';
import BsSelect from './bs-select/index';
import BsForm from './bs-form';
import BsDropdown from './bs-dropdown';
import BsDropdownTransition from './bs-dropdown-transition';
import BsPagination from './bs-pagination';
import BsBadge from './bs-badge/BsBadge.vue';
import BsMessage from './bs-message';
import BsBreadcrumb from './bs-breadcrumb';
import BsTag from './bs-tag';
import BsProgress from './bs-progress';
import BsTabs from './bs-tabs';
import BsSwitch from './bs-switch';
import BsMessageBox from './bs-message-box';
import BsAlert from './bs-alert';
import BsInputNumber from './bs-input-number';
import BsTooltip from './bs-tooltip';
import BsSlider from './bs-slider';
import BsModal from './bs-modal';
import BsDrawer from './bs-drawer';
import BsPopover from './bs-popover';
import BsSpinner from './bs-spinner';
import BsPopConfirm from './bs-pop-confirm';
import BsCollapse from './bs-collapse';
import BsCollapseTransition from './bs-collapse-transition';
import BsTree from './bs-tree';
import BsTreeSelect from './bs-tree-select';
import BsInputTags from './bs-input-tags';
import BsSelectInput from './bs-select-input';
import BsTimePicker from './bs-time-picker';
import BsDatePicker from './bs-date-picker';
import BsBackTop from './bs-backtop';
import BsLoading from './bs-loading';
import BsCascader from './bs-cascader';
import BsToast from './bs-toast';
import BsMenu from './bs-menu';
import BsConfigProvider from './bs-config-provider';
import BsRelativeTime from './bs-relative-time';

export default function (vueApp: any) {
  vueApp.component(BsButton.name, BsButton);
  vueApp.use(BsInput);
  vueApp.component(BsRadio.name, BsRadio);
  vueApp.component(BsRadioGroup.name, BsRadioGroup);
  vueApp.component(BsCheckbox.name, BsCheckbox);
  vueApp.component(BsCheckboxGroup.name, BsCheckboxGroup);
  vueApp.component(BsBadge.name, BsBadge);
  // vueApp.component(BsSelect.name, BsSelect);
  vueApp.use(BsSelect);
  vueApp.use(BsForm);
  vueApp.use(BsDropdown);
  vueApp.use(BsDropdownTransition);
  vueApp.use(BsPagination);
  vueApp.use(BsMessage);
  vueApp.use(BsBreadcrumb);
  vueApp.use(BsTag);
  vueApp.use(BsProgress);
  vueApp.use(BsTabs);
  vueApp.use(BsSwitch);
  vueApp.use(BsMessageBox);
  vueApp.use(BsAlert);
  vueApp.use(BsInputNumber);
  vueApp.use(BsTooltip);
  vueApp.use(BsSlider);
  vueApp.use(BsModal);
  vueApp.use(BsDrawer);
  vueApp.use(BsPopover);
  vueApp.use(BsSpinner);
  vueApp.use(BsPopConfirm);
  vueApp.use(BsCollapse);
  vueApp.use(BsCollapseTransition);
  vueApp.use(BsTree);
  vueApp.use(BsTreeSelect);
  vueApp.use(BsInputTags);
  vueApp.use(BsSelectInput);
  vueApp.use(BsTimePicker);
  vueApp.use(BsDatePicker);
  vueApp.use(BsBackTop);
  vueApp.use(BsLoading);
  vueApp.use(BsCascader);
  vueApp.use(BsButtonGroup);
  vueApp.use(BsToast);
  vueApp.use(BsMenu);
  vueApp.use(BsConfigProvider);
  vueApp.use(BsRelativeTime);
}
