import BsButton from './bs-button/BsButton.vue';
import BsButtonGroup from '@/components/bootstrap/bs-button-group';
import BsInput from './bs-input';
import BsIcon from './bs-icon/BsIcon.vue';
import BsRadio from './bs-radio/BsRadio.vue';
import BsRadioGroup from './bs-radio-group/BsRadioGroup.vue';
import BsCheckbox from './bs-checkbox/BsCheckbox.vue';
import BsCheckboxGroup from './bs-checkbox-group/BsCheckboxGroup.vue';
import BsSelect from './bs-select/index';
import BsForm from '@/components/bootstrap/bs-form';
import BsDropdown from '@/components/bootstrap/bs-dropdown';
import BsPagination from '@/components/bootstrap/bs-pagination';
import BsBadge from '@/components/bootstrap/bs-badge/BsBadge.vue';
import BsMessage from '@/components/bootstrap/bs-message';
import BsBreadcrumb from '@/components/bootstrap/bs-breadcrumb';
import BsTag from '@/components/bootstrap/bs-tag';
import BsProgress from '@/components/bootstrap/bs-progress';
import BsTabs from '@/components/bootstrap/bs-tabs';
import BsSwitch from '@/components/bootstrap/bs-switch';
import BsMessageBox from '@/components/bootstrap/bs-message-box';
import BsAlert from '@/components/bootstrap/bs-alert';
import BsInputNumber from '@/components/bootstrap/bs-input-number';
import BsTooltip from '@/components/bootstrap/bs-tooltip';
import BsSlider from '@/components/bootstrap/bs-slider';
import BsModal from '@/components/bootstrap/bs-modal';
import BsDrawer from '@/components/bootstrap/bs-drawer';
import BsPopover from '@/components/bootstrap/bs-popover';
import BsSpinner from '@/components/bootstrap/bs-spinner';
import BsPopConfirm from '@/components/bootstrap/bs-pop-confirm';
import BsCollapse from '@/components/bootstrap/bs-collapse';
import BsTree from '@/components/bootstrap/bs-tree';
import BsTreeSelect from '@/components/bootstrap/bs-tree-select';
import BsInputTags from '@/components/bootstrap/bs-input-tags';
import BsSelectInput from '@/components/bootstrap/bs-select-input';
import BsTimePicker from '@/components/bootstrap/bs-time-picker';
import BsDatePicker from '@/components/bootstrap/bs-date-picker';
import BsBackTop from '@/components/bootstrap/bs-backtop';
import BsLoading from '@/components/bootstrap/bs-loading';
import BsCascader from '@/components/bootstrap/bs-cascader';

export default function (vueApp: any) {
  vueApp.component(BsButton.name, BsButton);
  vueApp.use(BsInput);
  vueApp.component(BsIcon.name, BsIcon);
  vueApp.component(BsRadio.name, BsRadio);
  vueApp.component(BsRadioGroup.name, BsRadioGroup);
  vueApp.component(BsCheckbox.name, BsCheckbox);
  vueApp.component(BsCheckboxGroup.name, BsCheckboxGroup);
  vueApp.component(BsBadge.name, BsBadge);
  // vueApp.component(BsSelect.name, BsSelect);
  vueApp.use(BsSelect);
  vueApp.use(BsForm);
  vueApp.use(BsDropdown);
  vueApp.use(BsPagination);
  vueApp.use(BsMessage);
  vueApp.use(BsBreadcrumb);
  vueApp.use(BsTag);
  vueApp.use(BsProgress);
  vueApp.use(BsTabs);
  vueApp.use(BsSwitch);
  vueApp.use(BsMessageBox);
  vueApp.use(BsAlert);
  vueApp.use(BsInputNumber);
  vueApp.use(BsTooltip);
  vueApp.use(BsSlider);
  vueApp.use(BsModal);
  vueApp.use(BsDrawer);
  vueApp.use(BsPopover);
  vueApp.use(BsSpinner);
  vueApp.use(BsPopConfirm);
  vueApp.use(BsCollapse);
  vueApp.use(BsTree);
  vueApp.use(BsTreeSelect);
  vueApp.use(BsInputTags);
  vueApp.use(BsSelectInput);
  vueApp.use(BsTimePicker);
  vueApp.use(BsDatePicker);
  vueApp.use(BsBackTop);
  vueApp.use(BsLoading);
  vueApp.use(BsCascader);
  vueApp.use(BsButtonGroup);
}
